image: docker:24.0.6

services:
  - docker:24.0.6-dind

before_script:
  - apk add --no-cache docker-cli


stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the Docker image..."
    - docker build -t back-v1:${CI_COMMIT_SHA} .
  

deploy:
  stage: deploy
  script:
    - echo "Deploying the Docker image..."
    - docker login -u mrmahdifardi -p 9gdU9jib42RjAGVxA1! registry.hamdocker.ir/mrmahdifardi
    - docker tag myapp:${CI_COMMIT_SHA} CI_REGISTRY_IMAGE:latest
    - docker push CI_REGISTRY_IMAGE:latest

